services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  slowdash:
    image: slowproj/slowdash
    depends_on:
      - db
    #environment:
    #  - "SLOWDASH_INIT_DATASOURCE_URL=postgresql://myuser:mypassword@db:5432/mydatabase"
    #  - "SLOWDASH_INIT_TIMESERIES_SCHEMA=mytable[channel]@timestamp(aware)=value"
    ports:
      - "18881:18881"
    volumes:
      - ./SlowdashProject.yaml:/project/SlowdashProject.yaml

volumes:
  db_data:
