[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
