[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
WiringPi = "56b06491-0088-44d9-858f-9bc194f2c904"
