[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
WiringPi = "56b06491-0088-44d9-858f-9bc194f2c904"
